### ISSUE TITLE
Audit and update all zkApp docs for technical accuracy prior to hard fork

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#459]
Before the HF, verify technical content in the 35 zkApp topics

# Top-level zkApps topics in ./zkapps/: 
11 pages

1. [ ]  o1js FAQ #460
2. [ ]  How to Deploy a zkApp #461
3. [ ]  How to Test a zkApp #462
4. [ ]  How to Write a zkApp UI #463
5. [ ]  How to Write a zkApp #465
6. [ ]  How zkApps Work #466
7. [ ]  zkApps Overview #467
8. [ ]  zkApps Roadmap #468
9. [ ]  zkApps for Ethereum Developers #469
10. [ ]  zkApp CLI Installation 
11. [x]  zkApps Getting Started (new)

# o1js topics in ./zkapps/snarkyjs	
13 pages

1. [ ]  Actions & Reducer #470
2. [ ]  o1js Basic Concepts #471
3. [ ]  Custom Token API #472
4. [ ]  Events #473
5. [ ]  How to Fetch Events and Actions #474
6. [ ]  Introduction to o1js #475
7. [x]  Interacting With Mina #476
8. [ ]  Merkle Tree #477
9. [ ]  On-Chain Values #478
10. [ ]  Permissions #479
11. [ ]  Recursion #480
12. [ ]  Smart Contracts #481
13. [ ]  Time-Locked Accounts #482

# Tutorials in zkapps/tutorials
15 hefty pages

1. [x ]  zkApp Developer Tutorials 
2. [ ]  Tutorial 1: Hello World
3. [ ]  Tutorial 2: Private Inputs and Hash Functions
4. [ ]  Tutorial 3: Deploy to a Live Network 
5. [ ]  Tutorial 4: Build a zkApp UI in the Browser with React
6. [ ]  Tutorial 5: Common Types and Functions
7. [ ]  Tutorial 6: Off-Chain Storage
8. [ ]  Tutorial 7: Oracles
9. [ ]  Tutorial 8: Custom Tokens
10. [ ] Tutorial 9: Recursion
11. [ ]  Tutorial 10: Account Updates
12. [ ]  Tutorial 11: Advanced Account Updates
13. [ ]  Anonymous Message Board Tutorial
15. [ ]  Interacting with zkApps server-side
